# Core
db:
  redis:
    host : '127.0.0.1'
    port : 6379
    #emulate : true #set to false if redis server is on
    namespace : EG



crypto:
  cipherKey: sensitiveKey
  algorithm: aes256
  saltRounds: 10

# OAuth2 Settings
session:
  secret: keyboard cat
  resave: false
  saveUninitialized: false
accessTokens:
  timeToExpiry: 7200000
refreshTokens:
  timeToExpiry: 7200000
authorizationCodes:
  timeToExpiry: 300000
plugins:
  login-plugin: # "express-gateway-plugin-login"
    package: './plugin'
   